import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import Plotly from 'plotly.js-dist-min';
import { WellDetailPanel } from './WellDetailPanel';
import { useSessionStore } from '@/stores/session-store';
import { useSelectionStore } from '@/stores/selection-store';
import { useDataStore } from '@/stores/data-store';
import { useLanguageStore } from '@/stores/language-store';
import { getAmplification } from '@/lib/api';
vi.mock('plotly.js-dist-min', () => ({ default: { react: vi.fn(), relayout: vi.fn(), purge: vi.fn() } }));
vi.mock('@/lib/api', () => ({ getAmplification: vi.fn() }));
it('keeps compact populated fields visible and resizes the retained curve on disclosure without another request', async () => {
  useLanguageStore.getState().setLanguage('en');
  useSessionStore.setState({ sessionId: 's', sessionInfo: { session_id: 's', instrument: 'synthetic', allele2_dye: 'VIC', num_wells: 1, num_cycles: 2, has_rox: false, data_windows: null, suggested_cycle: 40, well_groups: null } });
  useSelectionStore.setState({ selectedWell: 'A1', currentCycle: 40 });
  useDataStore.setState({ scatterPoints: [{ well: 'A1', sample_name: 'Sample A', auto_cluster: 'Heterozygous', manual_type: null, confidence: 0.95, norm_fam: 1, norm_allele2: 1, raw_fam: 2, raw_allele2: 2, raw_rox: null }] });
  vi.mocked(getAmplification).mockResolvedValue({ allele2_dye: 'VIC', curves: [{ well: 'A1', cycles: [20, 40], norm_fam: [0, 1], norm_allele2: [0, 1] }] });
  const { container } = render(<WellDetailPanel />);
  await waitFor(() => expect(Plotly.react).toHaveBeenCalled());
  expect(screen.getByText('Sample A')).toBeVisible();
  expect(screen.getByText('95%')).toBeVisible();
  const details = container.querySelector('details')!;
  expect(details.open).toBe(false);
  const plot = container.querySelector('#amplification-plot');
  details.open = true; fireEvent(details, new Event('toggle'));
  expect(Plotly.relayout).toHaveBeenCalledWith(plot, { autosize: true });
  details.open = false; fireEvent(details, new Event('toggle'));
  expect(container.querySelector('#amplification-plot')).toBe(plot);
  expect(getAmplification).toHaveBeenCalledTimes(1);
});
