import { act, renderHook } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { useKeyboardAssignment } from './use-keyboard-assignment';
import { bulkSetWellTypes, getWellTypes } from '@/lib/api';
import { useAuthStore } from '@/stores/auth-store';
import { useSessionStore } from '@/stores/session-store';
import { useNavigationStore } from '@/stores/navigation-store';
import { useAnalysisStore } from '@/stores/analysis-store';
import { useSelectionStore } from '@/stores/selection-store';
import { useLanguageStore } from '@/stores/language-store';
vi.mock('@/lib/api', async original => ({ ...await original<typeof import('@/lib/api')>(), bulkSetWellTypes: vi.fn(), getWellTypes: vi.fn() }));
const saved = { assignments: { A1: 'NTC' }, manual_assignments: { A1: 'NTC' }, input_revision: 1 };
beforeEach(() => {
  vi.resetAllMocks();
  useSessionStore.getState().reset();
  useAuthStore.setState({ user: { id: 'owner', username: 'test', role: 'admin', display_name: null } });
  useLanguageStore.getState().setLanguage('en');
  useSessionStore.setState({ sessionId: 's', entryGeneration: 1 });
  useNavigationStore.setState({ session: 's', tab: 'analysis', status: 'ready', exportRestoring: false });
  useAnalysisStore.getState().setSession('s', 'owner');
  useAnalysisStore.getState().updateInputRevision('s', 'owner', 0);
  vi.mocked(getWellTypes).mockResolvedValue({ assignments: {}, manual_assignments: {}, input_revision: 0 });
  useSelectionStore.getState().selectWell('A1');
});
it('blocks duplicate mutations, retains selection on failure, and announces failure', async () => {
  let reject!: (error: Error) => void;
  vi.mocked(bulkSetWellTypes).mockReturnValue(new Promise((_, fail) => { reject = fail; }));
  const hook = renderHook(() => useKeyboardAssignment());
  act(() => { void hook.result.current.assign('NTC'); void hook.result.current.assign('Unknown'); });
  await act(async () => { await Promise.resolve(); });
  expect(bulkSetWellTypes).toHaveBeenCalledTimes(1);
  await act(async () => reject(new Error('offline')));
  expect(useSelectionStore.getState().selectedWells).toEqual(['A1']);
  expect(hook.result.current.message).not.toContain('offline');
  expect(hook.result.current.message).toContain('selection retained');
});
it('announces a successful assignment without clearing the selected wells', async () => {
  vi.mocked(bulkSetWellTypes).mockResolvedValue(saved);
  const hook = renderHook(() => useKeyboardAssignment());
  await act(async () => { await hook.result.current.assign('NTC'); });
  expect(hook.result.current.message).toBe('Type updated for 1 wells. Selection retained.');
  expect(useSelectionStore.getState().selectedWells).toEqual(['A1']);
});
it('shares a pending ticket across popup and global shortcut hook instances', async () => {
  let resolve!: (value: Awaited<ReturnType<typeof bulkSetWellTypes>>) => void;
  vi.mocked(bulkSetWellTypes).mockReturnValue(new Promise(done => { resolve = done; }));
  const popup = renderHook(() => useKeyboardAssignment());
  const global = renderHook(() => useKeyboardAssignment());
  act(() => { void popup.result.current.assign('NTC'); });
  popup.unmount();
  act(() => { void global.result.current.assign('Unknown'); });
  await act(async () => { await Promise.resolve(); });
  expect(bulkSetWellTypes).toHaveBeenCalledTimes(1);
  await act(async () => resolve(saved));
});
it('ignores late completion after session reentry and does not clear a new selection', async () => {
  let resolve!: (value: Awaited<ReturnType<typeof bulkSetWellTypes>>) => void;
  vi.mocked(bulkSetWellTypes).mockReturnValue(new Promise(done => { resolve = done; }));
  const hook = renderHook(() => useKeyboardAssignment());
  act(() => { void hook.result.current.assign('NTC'); });
  await act(async () => { await Promise.resolve(); });
  useSessionStore.setState({ entryGeneration: 2 });
  useSelectionStore.getState().selectWell('B1');
  await act(async () => resolve(saved));
  expect(useSelectionStore.getState().selectedWells).toEqual(['B1']);
  expect(hook.result.current.message).toBe('');
});
